reboot:
  # Service name as shown in UI
  name: Reboot
  # Description of the service
  description: Reboots the modem.

poll_now:
  # Service name as shown in UI
  name: Poll Now
  # Description of the service
  description: Polls the status of the modem immediately.
