wifi_on:
  description: Switches the WIFI on.
  fields:
    radio:
      description: Radio 2g, 5g or all
      example: "2g"
      
wifi_off:
  description: Switches the WIFI off.
  fields:
    radio:
      description: Radio 2g, 5g or all
      example: "2g"
