# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Deploy release

on:
  release:
    types: [ created ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Set version in manifest.json
        run: |
          sed -i 's/0.0.0/${{ steps.get_version.outputs.VERSION }}/g' ./custom_components/compal_wifi/manifest.json

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Zip
        run: |
          cd ./custom_components/compal_wifi
          zip compal_wifi.zip -r ./

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./custom_components/compal_wifi/compal_wifi.zip
          asset_name: compal_wifi.zip
          asset_content_type: application/zip
