name: HACS-Validation

on:
  workflow_dispatch:

jobs:
  hacs:
    name: HACS validation
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
